[rpc_endpoints]
pioneerDevnet = "http://127.0.0.1:38545"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = false
runs = 1000000



fs_permissions = [{ access = "read-write", path = "./results"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
